### PR TITLE
second try 

### PR DESCRIPTION
**Pull request by MandyPeng0529**
[new bellman.pdf](https://github.com/kbuzard/gradualism/files/1922242/new.bellman.pdf)
Hi, Professor Buzard 
     I tried to break the lines in 75-77 for the Euler, but it does not work somehow. Can you look at it to break the equation? 
Thanks

### CODE REVIEW

**Comment by kbuzard** [comment]
This should work: I've just replaced the first and last lines with the multline environment and I've added the paragraph break in the middle (with a hard return so you can see clearly where it is).

\begin{multline}
\frac{\partial A(m^\ast_t)}{\partial m^\ast_t} \cdot F^\alpha \cdot \left[(1-\delta)A(m^\ast_t)\cdot F^\alpha \cdot P^W\right]^\frac{1-\alpha}{\alpha}+ \\
\frac{\beta}{1-\beta}\cdot (1-\delta)\cdot\left[\frac{\partial A(m^\ast_{t+1})}{\partial m^\ast_{t+1}}\cdot F^\alpha \cdot \left(\frac{1-\alpha}{\alpha}\right)\cdot\left[(1-\delta)A(m^\ast_t)\cdot F^\alpha\cdot P^W\right]^\frac{1-\alpha}{\alpha}\cdot P^W-\delta\right]=\delta
\end{multline}

**Comment by MandyPeng0529** [comment]
I tried but does not work, on my editor, it shows "Package amsmath Error: \begin{multline} allowed only in paragraph mode. \begin{multline}." Also, how to put "Euler Equation" which is line 72 to start from the right-hand side instead of in the middle?

**Comment by kbuzard** [comment]
Did you REPLACE the \begin{align} with the \begin{multline} and the same thing with the \end statements? This error is the type of error that happens if you try to put multline inside of align. That won't work.

Delete the \[ and \] from around Euler Equation. Then put it inside flushright commands like this:

\begin{flushright}
Euler Equation
\end{flushright}

**Comment by MandyPeng0529** [comment]
There are several mistakes when I try to change the Euler and Multiline. Could you please look at them?

**Comment by kbuzard** [comment]
You should not have "\[" before or "\]" after either the Euler Equation line or the big equation.

This is why: "\[" is an abbreviation for "\begin{equation}" and "\]" is an abbreviation for "\end{equation}"

In the first case, you are using the text environment flushright instead of the equation environment, and in the second case, you are using the multline environment instead of the equation environment

**Comment by MandyPeng0529** [comment]
capture
Now the Errors are gone, but why nothing changed for the Euler and Equation?

**Comment by MandyPeng0529** [comment]
Sorry I mean left-justified, and now works, so does break the equation. The only thing is the right bracket disappear, but I already typed /right at the end of the equation. Otherwise, the Bellman is done.

**Pull request closed without merging**
