### PR TITLE
index

### PR DESCRIPTION
**Pull request by Nebhey**
This is an index for the data: all documents that can be used to do documents like for Haiti and Australia. 
I also updated the data document.

### CODE REVIEW

**Comment by kbuzard** [comment]
This is great! Amazing that there is not one country that reached an agreement with the U.S. in each of the first four rounds. Are there documents for the following three rounds?

One language thing. "Did not reached" should be "did not reach" throughout.

**Comment by Nebhey** [comment]
Yes, it is the exhaustive list of all document we have.

**Comment by Nebhey** [comment]
They are about the four first round: Geneva I, Annecy, Torquay and Geneva II. The other rounds wor a bit differently on the report documents.
I changed the language mistake.

**Comment by kbuzard** [comment]
That you for that clarification. I will be interested to hear what the other rounds look like when we meet on Wednesday.

I don't see a new commit for the language fix--should I wait for that before merging?

**Comment by Nebhey** [comment]
oups! I forgot to push, sorry, early morning.

**Pull request merged**
